-- Agregar campos de configuración de ticket POS a company_config
ALTER TABLE company_config
ADD COLUMN IF NOT EXISTS "showLogo" BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS "showNIT" BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS "showAddress" BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS "showPhone" BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS "showEmail" BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS "showWebsite" BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS "ticketWidth" VARCHAR(10) DEFAULT '80mm',
ADD COLUMN IF NOT EXISTS "fontSize" VARCHAR(10) DEFAULT 'medium',
ADD COLUMN IF NOT EXISTS "includeVendor" BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS "includeCashSession" BOOLEAN DEFAULT false;
