[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run railway:start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production" }

[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x", "openssl"]

[phases.build]
cmds = ["npm run railway:build"]
